#!/usr/bin/env bash
#
# configure_professional_ssh_server.sh
#
# PURPOSE:
#   Configures SSH server with professional-grade security settings.
#   Creates systemd service for persistent SSH tunnel with auto-restart.
#
# FEATURES:
#   - Key-based authentication (recommended)
#   - Hardened SSH configuration
#   - Systemd service for tunnel persistence
#   - Automatic reconnection on failure
#   - Comprehensive logging
#
# CLEAN CODE PRINCIPLES APPLIED:
#   - Reveals intention: "configure" + "professional_ssh_server" = production-ready setup
#   - One word per concept: "configure" for configuration tasks
#
# AUTHOR: TFG Team
# DATE: 2025-11-04

set -euo pipefail
IFS=$'\n\t'

# ============================================================================
# CONSTANTS
# ============================================================================

readonly SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
readonly SSH_CONFIG="/etc/ssh/sshd_config"
readonly SYSTEMD_SERVICE="/etc/systemd/system/ssh-tunnel.service"

# ============================================================================
# LOGGING
# ============================================================================

log_info() { echo "[INFO] ${1}" >&2; }
log_success() { echo "[SUCCESS] ${1}" >&2; }
log_error() { echo "[ERROR] ${1}" >&2; }
log_warning() { echo "[WARNING] ${1}" >&2; }

# ============================================================================
# VALIDATION
# ============================================================================

require_root_privileges() {
  if [[ "${EUID}" -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
  fi
}

# ============================================================================
# SSH HARDENING
# ============================================================================

harden_ssh_configuration() {
  log_info "Hardening SSH configuration for production use"

  # Backup original config
  cp "${SSH_CONFIG}" "${SSH_CONFIG}.bak.professional"

  # Apply hardening settings
  cat >> "${SSH_CONFIG}" <<'EOF'

# ============================================================================
# Professional SSH Server Configuration
# Generated by configure_professional_ssh_server.sh
# ============================================================================

# Listen on multiple ports for redundancy
Port 22
Port 53
Port 443

# Strong cryptography only
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication yes  # For Vagrant, disable in production
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Session settings
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
ClientAliveInterval 60
ClientAliveCountMax 3

# Security limits
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 60

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Allow tunnel for proxy
AllowTcpForwarding yes
GatewayPorts no
PermitTunnel no
EOF

  log_success "SSH configuration hardened"
}

restart_ssh_with_validation() {
  log_info "Validating and restarting SSH service"

  # Test configuration
  if sshd -t; then
    log_success "SSH configuration is valid"
  else
    log_error "SSH configuration has errors"
    exit 1
  fi

  # Restart service
  systemctl restart sshd || systemctl restart ssh
  log_success "SSH service restarted"
}

# ============================================================================
# SYSTEMD SERVICE
# ============================================================================

create_ssh_tunnel_systemd_service() {
  log_info "Creating systemd service for persistent SSH tunnel"

  cat > "${SYSTEMD_SERVICE}" <<'EOF'
[Unit]
Description=SSH SOCKS5 Tunnel Service
After=network.target sshd.service
Wants=network.target

[Service]
Type=simple
User=vagrant
Group=vagrant
Restart=always
RestartSec=10
StartLimitInterval=200
StartLimitBurst=5

# SSH tunnel command
ExecStart=/usr/bin/ssh -D 1080 -N -o ServerAliveInterval=60 -o ServerAliveCountMax=3 vagrant@localhost

# Security hardening
PrivateTmp=true
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=ssh-tunnel

[Install]
WantedBy=multi-user.target
EOF

  # Reload systemd
  systemctl daemon-reload

  # Enable and start service
  systemctl enable ssh-tunnel.service
  systemctl start ssh-tunnel.service

  log_success "Systemd service created and started"
}

verify_ssh_tunnel_service_status() {
  log_info "Verifying SSH tunnel service status"

  sleep 2  # Give service time to start

  if systemctl is-active --quiet ssh-tunnel.service; then
    log_success "SSH tunnel service is active and running"
    systemctl status ssh-tunnel.service --no-pager || true
  else
    log_warning "SSH tunnel service is not active"
    log_info "Check logs: sudo journalctl -u ssh-tunnel -n 50"
  fi
}

# ============================================================================
# MONITORING AND LOGGING
# ============================================================================

configure_enhanced_logging() {
  log_info "Configuring enhanced logging"

  # Create log directory
  mkdir -p /var/log/ssh-tunnel

  # Logrotate configuration
  cat > /etc/logrotate.d/ssh-tunnel <<'EOF'
/var/log/ssh-tunnel/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644 vagrant vagrant
}
EOF

  log_success "Enhanced logging configured"
}

create_monitoring_helper_scripts() {
  log_info "Creating monitoring helper scripts"

  # Status check script
  cat > /usr/local/bin/check-tunnel-status <<'EOF'
#!/usr/bin/env bash
# Quick status check for SSH tunnel

echo "═══ SSH Tunnel Service Status ═══"
systemctl status ssh-tunnel.service --no-pager

echo ""
echo "═══ Active SSH Connections ═══"
ss -tnp | grep ssh || echo "No active SSH connections"

echo ""
echo "═══ Recent Logs ═══"
journalctl -u ssh-tunnel -n 20 --no-pager
EOF

  chmod +x /usr/local/bin/check-tunnel-status
  log_success "Monitoring helper created: check-tunnel-status"
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
  log_info "Starting ${SCRIPT_NAME}"

  require_root_privileges

  harden_ssh_configuration
  restart_ssh_with_validation

  create_ssh_tunnel_systemd_service
  verify_ssh_tunnel_service_status

  configure_enhanced_logging
  create_monitoring_helper_scripts

  log_success "Professional SSH server configuration complete"

  cat <<EOF

╔═══════════════════════════════════════════════════════════════╗
║   Professional SSH Server - Configuration Complete           ║
╠═══════════════════════════════════════════════════════════════╣
║                                                               ║
║   SSH listening on ports: 22, 53, 443                         ║
║   Hardened configuration applied                              ║
║   Systemd service created: ssh-tunnel.service                 ║
║   Auto-restart enabled                                        ║
║                                                               ║
║   Check tunnel status:                                        ║
║   $ sudo systemctl status ssh-tunnel                          ║
║   $ check-tunnel-status                                       ║
║                                                               ║
║   View logs:                                                  ║
║   $ sudo journalctl -u ssh-tunnel -f                          ║
║                                                               ║
║   Restart tunnel:                                             ║
║   $ sudo systemctl restart ssh-tunnel                         ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝

EOF
}

main "$@"
