#!/usr/bin/env bash
#
# install_security_packages.sh
#
# PURPOSE:
#   Installs and configures essential security packages for production SSH servers.
#   Includes intrusion detection, firewall, and monitoring tools.
#
# PACKAGES INSTALLED:
#   - fail2ban: Brute-force protection
#   - ufw: Uncomplicated Firewall
#   - aide: Advanced Intrusion Detection Environment
#   - unattended-upgrades: Automatic security updates
#
# CLEAN CODE PRINCIPLES APPLIED:
#   - Reveals intention: "install" clearly indicates action, "security_packages" the target
#   - One word per concept: "install" for package installation
#   - Testable: Can run with --dry-run flag
#
# AUTHOR: TFG Team
# DATE: 2025-11-04

set -euo pipefail
IFS=$'\n\t'

# ============================================================================
# CONSTANTS
# ============================================================================

readonly SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
readonly FAIL2BAN_CONFIG="/etc/fail2ban/jail.local"
readonly UFW_CONFIG="/etc/ufw/ufw.conf"

# ============================================================================
# LOGGING
# ============================================================================

log_info() { echo "[INFO] ${1}" >&2; }
log_success() { echo "[SUCCESS] ${1}" >&2; }
log_error() { echo "[ERROR] ${1}" >&2; }
log_warning() { echo "[WARNING] ${1}" >&2; }

# ============================================================================
# VALIDATION
# ============================================================================

require_root_privileges() {
  if [[ "${EUID}" -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
  fi
}

# ============================================================================
# APT PACKAGE MANAGEMENT
# ============================================================================

update_package_repositories() {
  log_info "Updating package repositories"
  DEBIAN_FRONTEND=noninteractive apt-get update -qq
  log_success "Package repositories updated"
}

install_package_if_missing() {
  local package_name="${1}"

  if dpkg -l | grep -q "^ii  ${package_name} "; then
    log_info "${package_name} already installed"
  else
    log_info "Installing ${package_name}"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${package_name}"
    log_success "${package_name} installed"
  fi
}

# ============================================================================
# FAIL2BAN CONFIGURATION
# ============================================================================

configure_fail2ban_for_ssh_protection() {
  log_info "Configuring Fail2Ban for SSH protection"

  cat > "${FAIL2BAN_CONFIG}" <<'EOF'
# Fail2Ban configuration for SSH protection
# Auto-generated by install_security_packages.sh

[DEFAULT]
# Ban duration: 10 minutes
bantime = 600

# Find time window: 10 minutes
findtime = 600

# Max retries before ban
maxretry = 5

# Ignore localhost
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ssh,22,53,443
filter = sshd
logpath = /var/log/auth.log
maxretry = 5
bantime = 3600
EOF

  systemctl enable fail2ban
  systemctl restart fail2ban

  log_success "Fail2Ban configured and started"
}

verify_fail2ban_status() {
  log_info "Verifying Fail2Ban status"

  if systemctl is-active --quiet fail2ban; then
    log_success "Fail2Ban is active and running"

    # Show status
    fail2ban-client status sshd || true
  else
    log_error "Fail2Ban is not running"
    exit 1
  fi
}

# ============================================================================
# UFW FIREWALL CONFIGURATION
# ============================================================================

configure_ufw_firewall_rules() {
  log_info "Configuring UFW firewall"

  # Reset UFW to defaults
  ufw --force reset

  # Default policies
  ufw default deny incoming
  ufw default allow outgoing

  # Allow SSH on multiple ports
  ufw allow 22/tcp comment 'SSH default port'
  ufw allow 53/tcp comment 'SSH alternate port (DNS)'
  ufw allow 443/tcp comment 'SSH alternate port (HTTPS)'

  # Allow loopback
  ufw allow in on lo
  ufw allow out on lo

  # Enable UFW
  ufw --force enable

  log_success "UFW firewall configured and enabled"
}

verify_ufw_status() {
  log_info "Verifying UFW status"

  if ufw status | grep -q "Status: active"; then
    log_success "UFW is active"
    ufw status verbose
  else
    log_error "UFW is not active"
    exit 1
  fi
}

# ============================================================================
# AIDE INTRUSION DETECTION
# ============================================================================

initialize_aide_database() {
  log_info "Initializing AIDE database (this may take a few minutes)"

  # Initialize database
  aideinit || true

  if [[ -f "/var/lib/aide/aide.db.new" ]]; then
    mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
    log_success "AIDE database initialized"
  else
    log_warning "AIDE database initialization skipped (slow in VM)"
  fi
}

# ============================================================================
# UNATTENDED UPGRADES
# ============================================================================

configure_automatic_security_updates() {
  log_info "Configuring automatic security updates"

  cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
// Automatic security updates configuration
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

  log_success "Automatic security updates configured"
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
  log_info "Starting ${SCRIPT_NAME}"

  require_root_privileges
  update_package_repositories

  # Install security packages
  install_package_if_missing "fail2ban"
  install_package_if_missing "ufw"
  install_package_if_missing "aide"
  install_package_if_missing "unattended-upgrades"

  # Configure services
  configure_fail2ban_for_ssh_protection
  verify_fail2ban_status

  configure_ufw_firewall_rules
  verify_ufw_status

  initialize_aide_database
  configure_automatic_security_updates

  log_success "All security packages installed and configured"

  cat <<EOF

╔═══════════════════════════════════════════════════════════════╗
║   Security Packages Installed                                 ║
╠═══════════════════════════════════════════════════════════════╣
║                                                               ║
║   ✓ Fail2Ban (brute-force protection)                         ║
║   ✓ UFW (firewall)                                            ║
║   ✓ AIDE (intrusion detection)                                ║
║   ✓ Unattended-upgrades (automatic security updates)          ║
║                                                               ║
║   Check status:                                               ║
║   $ sudo systemctl status fail2ban                            ║
║   $ sudo ufw status verbose                                   ║
║                                                               ║
║   View Fail2Ban jails:                                        ║
║   $ sudo fail2ban-client status                               ║
║   $ sudo fail2ban-client status sshd                          ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝

EOF
}

main "$@"
